### ISSUE TITLE
Add query action

### ISSUE THREAD

**Issue by GMS103** [lvjr/texfindpkg#1]
Hi, thanks for this tool.
Would it be possible to add an option ```dry``` to show what would be done without actually doing it?

**Comment by lvjr** [comment]
Ok, I will add `query` action in next release.

**Comment by lvjr** [comment]
I have renamed `findpkg` to `texfindpkg` and added `query` action. The new release has been included in TeX Live. Now you can run
```
texfindpkg query \fakeverb
```

**Comment by lvjr** [comment]
I have renamed `findpkg` to `texfindpkg` and added `query` action. The new release has been included in TeX Live. Now you can run
```
texfindpkg query \fakeverb
```
