### ISSUE TITLE
Only alphabetically first package/class defining a command is found

### ISSUE THREAD

**Issue by amunn** [lvjr/texfindpkg#5]
Thanks for writing this, it has a lot of potential. Right now, however, only the first package or class to define a command is found.

E.g. 

`texfindpkg query '\chapter'` finds `amsbook.cls` but not `book`, `memoir` etc. 
`texfindpkg query '\Tree'` finds `logicpuzzles` but not `qtree`, `tikz-qtree`, `xyling` etc. 

I suspect that for the command finding function, finding dependencies is less important than finding the package(s) that define the command, since most people I suspect have a fairly complete distribution installed anyway.

**Comment by lvjr** [comment]
I will fix this issue in next release.

**Comment by lvjr** [comment]
I have uploaded version 2023E to CTAN.
