### ISSUE TITLE
miktex-installed texfindpkg fails

### ISSUE THREAD

**Issue by mbertucci47** [lvjr/texfindpkg#6]
texfindpkg was recently added to miktex so I installed it through the console on my Windows machine, however there seems to be a packaging error (or some other kind of error). Running
```
texfindpkg query -f array.sty
```
in a terminal produces
```
texfindpkg: security risk: running with elevated privileges
[tfp] you are using miktex
...\Local\Programs\MiKTeX\scripts/texfindpkg\texfindpkg.lua:78: bad argument #1 to 'open' (string expected, got nil)
```
Not sure if this is a miktex or texfindpkg issue.

**Comment by lvjr** [comment]
After installing `texfindpkg` on my Windows machine, I discovered that MiKTeX didn't create an executable file `texfindpkg.exe` in `texmfs\install\miktex\bin\x64` folder, therefore I could not even run `texfindpkg query -f array.sty`.

Could you check again whether there is `texfindpkg.exe` in your `texmfs\install\miktex\bin\x64` folder. If not, this is a MiKTeX bug.

**Comment by mbertucci47** [comment]
I do have a `texfindpkg.exe`, in the folder `C:\Users\<user>\AppData\Local\Programs\MiKTeX\miktex\bin\x64`.

**Comment by lvjr** [comment]
I am using MiKTeX portable. Maybe this causes the difference. I will install a normal MiKTeX and test `texfindpkg` on it later.

**Comment by lvjr** [comment]
@mbertucci47 I have created an issue here [https://github.com/MiKTeX/miktex-packaging/issues/360](https://github.com/MiKTeX/miktex-packaging/issues/360).

**Comment by lvjr** [comment]
After moving `texfindpkg.json.gz` to `C:\Users\<user>\AppData\Local\Programs\MiKTeX\tex\latex\texfindpkg` folder and refreshing filename database, TeXFindPkg runs well:
```
C:\Windows\system32>texfindpkg query -f array.sty
[tfp] you are using miktex
[tfp] ================================================
[tfp] building dependency tree for array.sty:
[tfp] ------------------------
[tfp] array.sty (from latex-tools)
[tfp] ------------------------
[tfp] miktex package needed: latex-tools
[tfp] this package is already installed
```

**Comment by mbertucci47** [comment]
Yes that works for me too

**Comment by mbertucci47** [comment]
Fixed with recent miktex update. It now places `texfindpkg.json.gz` in `.../MiKTeX/tex/support/texfindpkg`.
